### ISSUE TITLE
Marker disappeared in the heatmap

### ISSUE THREAD

**Issue by giuliospinozzi** [BodenmillerGroup/IMCDataAnalysis#100]
When I try to generate the first heatmap with the following code (image attached):

`dittoHeatmap(spe[,cur_cells], treeheight_row=0,  treeheight_col=0, genes = rownames(spe)[rowData(spe)$use_channel],
             assay = "exprs", cluster_cols = F, scale = "none",
             heatmap.colors = colorRampPalette(colors = turbo_colormap_data_HEX)(100), annot.by = "patient_id",
             annotation_colors = list(patient_id = col_sample_id),clustering_callback = callback_rev)`

Sometimes a specific marker is not printed (but in the rowData(spe) is present). Privately we can discuss (I would not public our data here)

**Comment by SchulzDan** [comment]
Hi @giuliospinozzi,

it is impossible to reproduce what kind of problem you have here from what you provide. also, you are specifically using a `dittoHeatmap` function here which comes from the `dittoSeq` package. So maybe better to provide a reproducible issue on their side.
Best,
Daniel

**Comment by giuliospinozzi** [comment]
Hi,
We have RData, but is huge, can we share with you the data and the script?

BR
G

**Comment by nilseling** [comment]
Linking it here: https://github.com/dtm2451/dittoSeq/issues/146

**Comment by giuliospinozzi** [comment]
I have the reason. Was the hot pixel filter with tophat.
Thanks for the help, we can close.
