### ISSUE TITLE
Phenograph Clustering

### ISSUE THREAD

**Issue by tbudiman7** [BodenmillerGroup/IMCDataAnalysis#102]
Hi Bodenmiller Lab,

I had a question regarding phenograph clustering. In this section of the script to demonstrate phenograph clustering before batch correction, a condition is applied to only use certain channels to perform clustering:
mat <- t(assay(spe, "exprs")[rowData(spe)$use_channel,])

However, in the next section the condition is not applied:
mat <- reducedDim(spe, "fastMNN")

Is there a reason the condition to not use certain channels not applied? To my understanding the DNA and membrane channels should be excluded in this step as well. If we wanted to exclude certain channels from clustering would we add that code of the script in this step as well or would that have to be applied prior to this? Thank you.

**Comment by SchulzDan** [comment]
Hi @tbudiman7,
calling the matrix of the reduced dimensions here simply gets that information which has been precalculated and stored in the spe object. If you check in section [8.1](https://bodenmillergroup.github.io/IMCDataAnalysis/batch-effects.html#fastmnn-correction) you can see that indeed the same set of markers was used to calculate the batch corrected low dimensional representation.
Best,
Daniel
