### ISSUE TITLE
Running stats on marker expression between groups

### ISSUE THREAD

**Issue by rebekahdadey** [BodenmillerGroup/IMCDataAnalysis#103]
Hello! Thanks so much for your great tools for IMC analysis. I'm currently working on your [single cell visualization module](https://bodenmillergroup.github.io/IMCDataAnalysis/single-cell-visualization.html) and am having trouble how to figure out run stats on marker expression. 
I'm specifically looking at the use of ```plotPbExprs```to compare marker expression within each cell type comparing conditions. Using the example below, I'd like to know if expression of each marker (MPO, SMA, etc) is significantly different when I compare BCC to CRC in B cells, for example. Is there a way to easily perform this? Or is there a way to export the median expression for each of these conditions and markers for each cell type so I may do that separately?
<img width="573" alt="Screen Shot 2024-07-30 at 12 20 09 PM" src="https://github.com/user-attachments/assets/21b515d2-0c89-475a-9484-351a07334c38">

**Comment by SchulzDan** [comment]
Hi @rebekahdadey,
slightly sorry for the late reply, but your question is not really related to our package. I will give my thoughts below and then close the issue.
The functionality of this specific plot does to my knowledge not allow direct statistical comparison. For your taks I would aggregate the expression of each marker across all cell types and cancer indications and then run simple statistical comparisons (e.g. Wilcoxon rank sum test) across all markers and cell types. You will likely have to p.value correct as well. You could then visualize these results e.g. as a circle plot where you size the circles according to the fold change and color them according to the p.value or FDR. For simple, comparisons in ggplot you can also look into `stat_compare_means` function from the `ggpubr` library. Hope that helps you.
Best,
Daniel
