### ISSUE TITLE
Writing out compensated images as TIFF files

### ISSUE THREAD

**Issue by rahilgholami** [BodenmillerGroup/IMCDataAnalysis#104]
Dear @nilseling,

I have a problem regarding saving the compensated images. I am saving them using the commands you provided.

> library(tiff)
dir.create("data/comp_img")
lapply(names(images_comp), function(x){
  writeImage(as.array(images_comp[[x]])/(2^16 - 1), 
             paste0("data/comp_img/", x, ".tiff"),
             bits.per.sample = 16)
})

Typically, pixel intensities are not integers, even before compensation—they are of type float. When I read the uncompensated images (outputs of the Steinbock pipeline) using `loadImages`, everything works fine (I also verified this using `tifffile.imread`). However, after saving the compensated images and reading them back using `loadImages(..., as.is=TRUE)`, I noticed that the decimal points are clipped. I'm unsure whether I'm making a mistake or if there's a limitation. Is there any way to preserve the decimal values?

Thank you in advance,
Rahil

**Comment by nilseling** [comment]
Hi @rahilgholami 
that is correct. Here you are saving the images as 16-bit unsigned integers. Back then I think I couldn't find a good way to write out 32-bit floats (that is official supported) but you can try setting `bits.per.sample=32` - make sure to adjust the transformation of the images and check again by reading in the images. There are also other packages around to write out images. But I haven't come across a setting where the decimals mattered.

**Comment by rahilgholami** [comment]
I really appreciate your response! 
I also tried setting `bits_per_sample=32`, but it didn't work as I expected. I checked other packages as well, but each has limitations—either with the number of channels or expecting an integer-valued array.

**Comment by nilseling** [comment]
Yeah, I had the feeling that this wasn't trivial. That's why I stuck with the 16-bit encoding. For us it was always fine to clip the values. Sorry for not being more helpful here. I'll close this issue as I don't see an easy way to implement this.
