### ISSUE TITLE
Question regarding treatment and data structure

### ISSUE THREAD

**Issue by Shawnmhy** [BodenmillerGroup/IMCDataAnalysis#14]
Wonderful paper, congratulations! I have two questions regarding the studied cohort:

1. What is the treatment provided for the patients? Is it immunotherapy or just standard of care?
2. I understand that there are 2 compartments for each core: epithelial and non-epithelial and there are two panels of cell types associated with each compartment. However, how could I tell which are tumor cells?
3. I imported the cell mask into the matlab and observed that the integer assigned to each pixel is not in order. For example, for the cell mask for core MB0000_64, the integers are 232 (smallest), 464, 697, ..., etc), instead of 1, 2, 3, 4..... Why is that?

Thank you for answering the questions!

**Comment by nilseling** [comment]
Hi @Shawnmhy, 
I have transfered the issue to here as it it not directly related to the `ImcSegmentationPipeline`. First, I would like to make sure which samples you mean. Are these the ones provided as example data for the segmentation pipeline available at https://zenodo.org/record/5949116? 

1. If so, we currently do not have treatment information available for these patients. Treatment will also not be part of the example analysis as you would usually need more patients for this.
2. This repository here hosts an example analysis workflow for these patient samples. Over the next week I will add a section which explains how to label these cells.
3. The ID `MB0000_64` does not exist in the dataset - could you please specify which data you mean?
Thanks,
Nils

**Comment by Shawnmhy** [comment]
Hi Nils,
Thank you for your reply.
I meant the dataset that has been analyzed in the Nature Genetics paper (https://doi.org/10.1038/s41588-022-01041-y)
Here is the Zenodo link for that dataset: https://doi.org/10.5281/zenodo.5850952

**Comment by nilseling** [comment]
Ok, I see. The `ImcSegmentationPipeline` is not the repository associated to the publication. You would need to contact the corresponding author to clarify your questions.
