### ISSUE TITLE
Add section to write out spillover corrected images

### ISSUE THREAD

**Issue by nilseling** [BodenmillerGroup/IMCDataAnalysis#19]
Might be helpful for the user to see how to write out 16-bit spillover compensated .tiff files

**Comment by PingjunChen** [comment]
@nilseling On the section "6.4 Write out compensated images", I believe that `as.array(images_comp[[x]])/(2^16 - 1)` shall be `as.array(images_comp[[x]])*(2^16 - 1)`.

**Comment by nilseling** [comment]
In that section `as.array(images_comp[[x]])/(2^16 - 1)` is correct. The actual pixel values of the compensated images are distributed between 0 and a few thousand counts. So if you would multiply the images by 65535 you would generate values >> 65535 (the maximum integer that 16-bit images can store). Here, the images are divided by 65535 to generate pixel values that lie between 0-1. By default, the `writeImage` assumes that pixel values are distributed between 0-1 and would clip values > 1.

**Comment by PingjunChen** [comment]
For my image, when it is loaded, the range is between 0 and 1, and after the spillover compensation, it is still in the range of 0 and 1. So dividing (2^16 - 1) doesn't make sense on my data. While if the loaded image has values ranging from 0 to 65536, then you are absolutely correct. Thanks.

**Comment by PingjunChen** [comment]
For my case, I shall not multiple 2^16 - 1. The saved tiff via `writeImage` seems would multiple 2^16 - 1 in the saving process. While if your original intensity is between 0 and a few thousand counts, instead of between 0-1, then dividing (2^16 - 1) is needed .

**Comment by nilseling** [comment]
Ok, I see. It seems that you are not reading in the correct counts. For reading in 16 bit images, please set `as.is = TRUE` in the `loadImages` function.

**Comment by PingjunChen** [comment]
Right, the image intensity corresponds to the counts, after setting the parameter `as.is = TRUE` when using `loadImages`. Thanks.

**Comment by nilseling** [comment]
That's only needed when reading in 16 bit images. `steinbock` writes out 32 bit images which can be read in as is.

**Comment by nilseling** [comment]
Done in #25
