### ISSUE TITLE
RNA detection in IMC

### ISSUE THREAD

**Issue by SchulzDan** [BodenmillerGroup/IMCDataAnalysis#2]

**Comment by nilseling** [comment]
Could you give a short description on what you mean? I assume this refers to identifying expressing cells compared to a control? Or do you mean the community detection?

**Comment by nilseling** [comment]
@SchulzDan do you think that's still necessary here? If not I'd close the issue.

**Comment by nilseling** [comment]
Closing as this is a bit too custom.
