### ISSUE TITLE
Can a fullstack.tiff converted to visualize data?

### ISSUE THREAD

**Issue by Jiyishuai** [BodenmillerGroup/IMCDataAnalysis#21]
Helllo. Thank you for developiong this amazing IMC data analysis pipeline. Recently there is a research deposited IMC data of breast tumor tissue from patients recruited to the METABRIC study, which previously generated available genomic data. (_Danenberg E, et al. Nat Genet. 2022_) The authors had deposited imaging mass cytometry data, derived images and processed single-cell data, contains three types:
Full stack tiff images that contain multiplexed IMC images.
Image masks that identify image regions associated with cells, epithelium and vessels
Processed data that contain measurements taken using the associated images

So I want to consult if there is anyway to visualize the specific markers by using the data they deposited? 
Here is the link to IMCdata: https://zenodo.org/record/6036188#.YrwBSXZBxD8
Thank you very much !

**Comment by nilseling** [comment]
Hi @Jiyishuai

thanks for reaching out. you can visualize multichannel imaging data using [cytomapper](https://www.bioconductor.org/packages/release/bioc/html/cytomapper.html) in R. Buy in general you can use a number of open source tools such as [napari](https://napari.org/), [FIJI](https://imagej.net/software/fiji/) or [QuPATH](https://qupath.github.io/) to visualize the data interactively. Have a look at the [Read in images](https://bodenmillergroup.github.io/IMCDataAnalysis/read-data.html#read-images) and [Image visualization](https://bodenmillergroup.github.io/IMCDataAnalysis/image-visualization.html) sections if you want to visualize it in R.

**Comment by nilseling** [comment]
Assuming this has been resolved. Please reopen if there are issues.
