### ISSUE TITLE
Spillover matrix estimation cannot proceed after the optional pixel binning

### ISSUE THREAD

**Issue by PingjunChen** [BodenmillerGroup/IMCDataAnalysis#23]
Hey,

I try applying pixel binning before spillover estimation to increase the robustness of the estimated spillover matrix with the following code snippet.

```
library(imcRtools)
library(CATALYST)
library(pheatmap)

# load single-metal spots
sce <- readSCEfromTXT("data/lung") 
# asinh-transform the data using a cofactor of 5
assay(sce, "exprs") <- asinh(counts(sce)/5)

bin_size = 10
sce <- binAcrossPixels(sce, bin_size = bin_size)

# Filtering incorrectly assigned pixels
bc_key <- as.numeric(unique(sce$sample_mass))
bc_key <- bc_key[order(bc_key)]
sce <- assignPrelim(sce, bc_key = bc_key)
sce <- estCutoffs(sce)
sce <- applyCutoffs(sce)
rowData(sce)$is_bc <- TRUE # to make sure all antibodies show up

# cur_table <- table(sce$bc_id, sce$sample_mass)
# pheatmap(log10(cur_table + 1), cluster_rows = FALSE, cluster_cols = FALSE)
# sce <- filterPixels(sce, minevents = 40, correct_pixels = TRUE)

# Compute spillover matrix
sce <- computeSpillmat(sce)
```
While I obtain the following errors on `assignPrelim` after using the `binAcrossPixels` function.

**Error in .check_assay(u$x, u$assay) : 
  sum(y == assayNames(x)) == 1 is not TRUE**

While the code runs just fun when I have commented on the line of code `binAcrossPixels`.

**Comment by nilseling** [comment]
This is CATALYSTs way of telling you that the default assay `exprs` is missing in the object. Please have a look at the `assignPrelim` documentation and the `sce` object after binning. So after calling `assay(sce, "exprs") <- asinh(counts(sce)/5)` the spillover estimation works using the code you have posted.

**Comment by PingjunChen** [comment]
@nilseling I just tried moving  `assay(sce, "exprs") <- asinh(counts(sce)/5)` after the pixel binning operation, then the spillover matrix estimation works.  Thanks for your suggestion.

**Comment by nilseling** [comment]
That's great! Closing
