### ISSUE TITLE
Spatial community analysis

### ISSUE THREAD

**Issue by StefanosVoglis** [BodenmillerGroup/IMCDataAnalysis#29]
@nilseling, as discussed:

By constructing the graph from the colPair edge list with `graph_from_edgelist(as.matrix(colPair(stroma_sce, "neighborhood")), directed = FALSE)` without specifying the number of nodes, the number of cells in stroma_sce can be != to the number of cells which the communities got assigned to (comm_stroma). This occurs after subsetting the original sce object. 

Your workaround was: 
`gr <- graph_from_data_frame(as.data.frame(colPair(stroma_sce, "neighborhood")), 
                            directed = FALSE, vertices = data.frame(index = 1:ncol(stroma_sce)))`

**Comment by nilseling** [comment]
Fixed in #28
