### ISSUE TITLE
Add `iSEE` to single-cell visualization section

### ISSUE THREAD

**Issue by nilseling** [BodenmillerGroup/IMCDataAnalysis#32]
Could be something that @lassedochreden can do ;) I think it might be nice to add a chunk like

```
if (interactive()) {
    iSEE(spe, ...)
}
```

At the end to point users to the interactive visualization option.

**Comment by lassedochreden** [comment]
Yes! Will add this and do some other fixes in branch `single_cell_viz_fix`.

**Comment by nilseling** [comment]
Done in #43
