### ISSUE TITLE
normalising IMC data

### ISSUE THREAD

**Issue by rahilgholami** [BodenmillerGroup/IMCDataAnalysis#36]
Hi @nilseling 

I have a question regarding normalising expressions for Quality Control or other downstream tasks.
After applying inverse hyperbolic sine function still channel values belong to different ranges which can make some bias for further analysis like SNR plot in Quality Control. If someone normalises (min-max scaling and clipping) the images before calculating the signal-to-noise ratio, the results will change mostly on signal intensity axis. 
What would you recommend? 

I see that you take `normalize` from `cytomapper` to normalise (min-max scaling and clipping) the images. For centring and scaling (unit variance)  the channels I couldn't find any function to apply to images. Should do it manually or there is a function for that?

Best,
Rahil

**Comment by nilseling** [comment]
Hi @rahilgholami 
that's a good question! And indeed we don't really discuss all possible ways of data normalization.
As you point out the `asinh` transformation does not bring marker intensities to similar ranges but rather squeezes the range. Abundant markers will still dominate downstream analysis such as clustering. 
If you perform feature scaling (min-max) you bring all channels to the same range but you will likely enhance signal that is not there if some of your markers are not expressed/detected. So it's a bit up to you which type of transformation/scaling you want to use on your data. Tbh, the cleanest way to calculate the SNR is on the raw counts without any transformation/scaling but automatic detection of positive/negative cells is challenging. 
For the image level we don't provide other normalization functions as a standardization of the pixel intensities is something that is not commonly done. You could apply a `sqrt` transformation to the images - this is something that some people do.

So all in all: there are different ways of normalizing the data but not necessarily a "best" way. You will need to test different approaches and see if your biological interpretation is robust.
Best,

Nils

**Comment by rahilgholami** [comment]
Thank you @nilseling for the comprehensive explanation!

Best,
Rahil
