### ISSUE TITLE
Segmenting multinucleated cells

### ISSUE THREAD

**Issue by rahilgholami** [BodenmillerGroup/IMCDataAnalysis#39]
Hi @nilseling 

I have a question regarding challenging cell types such as macrophages and fibroblasts which are multinucleated.
These cell types are segmented sub-optimally using mesmer. Since we are using a pre-trained network to segment the cells the quality of segmentation  highly depends on the present cell types in the training images.
 
An alternative solution could be using Cell profiler + Ilastik which can learn multinucleated cells by manually annotating multinuclear cells.  

What would you suggest for such cell types if someone would like to use mesmer for segmentation?

Best,
Rahil

**Comment by nilseling** [comment]
Hi @rahilgholami 
as you said, Mesmer is pre-trained and might therefore under-perform when segmenting less common cells or unseen tissues. Unfortunately, you would need to follow the [IMC segmentation pipeline](https://github.com/BodenmillerGroup/ImcSegmentationPipeline) to perform custom segmentation using CellProfiler and Ilastik. Have a look at [read_cpout](https://bodenmillergroup.github.io/imcRtools/reference/read_cpout.html) of the `imcRtools` package for reading the resulting data into R. You can then always follow the downstream analysis.

**Comment by rahilgholami** [comment]
Thank you for the informtion!

**Comment by nilseling** [comment]
Assuming this is resolved - closing now
