### ISSUE TITLE
Read spatial masks into the spe object

### ISSUE THREAD

**Issue by Hllshd** [BodenmillerGroup/IMCDataAnalysis#46]
Hi @nilseling and everyone

I'm trying to add regional masks to my workflow to account for the location of cells in the tumor, stroma or non-malignant tissue. Therefore I created two masks, one was exported as "simple segmentation" 16-bit .tiff images from Ilastik, the other ones are 16-bit .tiff images as well and were created with a custom workflow. When I open the regional masks in imageJ, pixels may have the values 1 or 2 for the Ilastik masks, and 26 or 51 for the other masks while the X and Y coordinates are identical to the cell mask. Ideally I would be able to add this information as features for each cell into the spe and be able to "gate" on the corresponding location.

I used the steinbock utils match function to identify overlapping objects but now I'm unsure about how to import the masks into the spe object.

I tried creating a spe object using the cytomapper measureObjects function with the regional masks as "images" and the cell masks as "masks" but get this error:
Error in seq_len(dim(image[[1]])[3]) : 
  argument must be coercible to non-negative integer

When using the Ilastik probabilities instead, creating the spe works but the probabilities aren't translated into exprs assays. 

I also tried to measure the intensities in steinbock but receive an error: IndexError: index 1 is out of bounds for axis 0 with size 1

I think it must be something with the format of the mask files, but I'm not sure what exactly. Somehow the values aren't recognized as integer I guess. 

Any help or tips would be much appreciated.

Thanks
Henrike

**Comment by nilseling** [comment]
Hi @Hllshd 

thanks for reaching out! I was able the verify the `measureObjects` bug. Could you please set the `channelNames` of the region masks object:

```
channelNames(region_masks) <- "region_mask"
```

This should fix the issue with the `measureObjects` function and you should be able to link each cell to your tissue region. Of note: I would recommend calling `measureObjects(cell_mask, region_masks, basic_feature = "q05", basic_quantiles = 0.5)` to measure the median instead of the mean.

**Comment by Hllshd** [comment]
Hi Nils

Thanks so much for the quick reply! Your suggestion worked!

I noticed that the assays are now called "counts_q05" when using the median (which I would indeed prefer) in the measureObjects function. Is it possible to rename the assays into "counts" so that I can merge them with the spe created from the image stacks using the rbind function?

**Comment by nilseling** [comment]
Yes, you can rename the assay slot via `assayNames(spe) <- "counts"`. Please make sure the cells in both objects have the same order.

**Comment by Hllshd** [comment]
Great, thanks so much!

**Comment by nilseling** [comment]
Great that this worked! Closing the issue now - feel free to reopen if there are still issues or open a new one.
