### ISSUE TITLE
Rphenograph clustering codes not working

### ISSUE THREAD

**Issue by zoqaiyum** [BodenmillerGroup/IMCDataAnalysis#54]
Hi @nilseling 

I created an "sce" object for my images and masks and now I am following this protocol (https://bodenmillergroup.github.io/IMCDataAnalysis/cell-phenotyping.html#clustering) to perform clustering using Rphenograph (section 9.2.1). 

Using your code, I simply replaced "spe" to "sce" since my object is a single class experiment object but I am getting the following error: 

<img width="969" alt="Screenshot 2023-04-21 at 3 35 45 PM" src="https://user-images.githubusercontent.com/119648999/233720630-cefcde67-827e-48a0-ae71-44fdc32abb9e.png">

It appears that there is no "exprs" in my sce object. How should I proceed?

Many thanks.

**Comment by nilseling** [comment]
Please read through one of the earlier sections on data transformation: https://bodenmillergroup.github.io/IMCDataAnalysis/read-data.html
