### ISSUE TITLE
Transformation of IMC data

### ISSUE THREAD

**Issue by zoqaiyum** [BodenmillerGroup/IMCDataAnalysis#55]
Hi @nilseling 

I am using the IMC guide (https://bodenmillergroup.github.io/IMCDataAnalysis/read-data.html#cell-processing) for transforming data. 

My untransformed data looks like this: 
```
library(dittoSeq)
dittoRidgePlot(sce, var = "CD3-170Er", group.by = "sample_id", assay = "counts") +
    ggtitle("CD3 - before transformation")
```
<img width="734" alt="Screenshot 2023-04-24 at 3 27 24 PM" src="https://user-images.githubusercontent.com/119648999/234096320-d638772f-db58-4dc7-ae2a-ad93feb418fe.png">

Transforming using arcsinh cofactor 1 looks like this: 
```
assay(sce, "exprs") <- asinh(counts(sce)/1)
dittoRidgePlot(sce, var = "CD3-170Er", group.by = "sample_id", assay = "exprs") +
    ggtitle("CD3 - after transformation")
```
<img width="730" alt="Screenshot 2023-04-24 at 3 28 55 PM" src="https://user-images.githubusercontent.com/119648999/234096688-356ab8b9-ea36-45c8-b3ec-7d033f473b10.png">

Log transformation + 0.01 looks like this: 
```
assay(sce, "exprs") <- log(counts(sce) + 0.01)
dittoRidgePlot(sce, var = "CD3-170Er", group.by = "sample_id", assay = "exprs") +
    ggtitle("CD3 - after transformation")
```

<img width="720" alt="Screenshot 2023-04-24 at 3 32 10 PM" src="https://user-images.githubusercontent.com/119648999/234097393-117081ed-7811-425b-9d11-444d76ed955c.png">

It appears that arcsinh transformation with cofactor 1 didn't help, but log transforming my data resulted in negative and positive peaks. Are these log transformed peaks considered an acceptable representation of the transformation? My x axis is all in the negative now though so does this matter? If so, how do I fix the scaling?

Thanks!

**Comment by nilseling** [comment]
Hi @zoqaiyum 

as you can see, the mean pixel intensities are quite low (< 1). So the arsinh transformation does not transform the counts using the chosen co-factor as only counts larger than the co-factor are roughly log-transformed. In your case you can also try using a smaller co-factor (e.g. 0.1). While there is no optimal transformation you will need to check how downstream analysis is affected by the different transformations you picked.

**Comment by zoqaiyum** [comment]
Hi @nilseling 

Many thanks for the tip. I am trying some different transformations with different co-factors. 

Co-factor 0.1: 
<img width="752" alt="Screenshot 2023-04-25 at 1 19 29 PM" src="https://user-images.githubusercontent.com/119648999/234354959-3d414615-1245-47d5-9988-886483ec498d.png">


Co-factor 0.05: 
<img width="756" alt="Screenshot 2023-04-25 at 1 27 14 PM" src="https://user-images.githubusercontent.com/119648999/234355493-298f5574-b32a-4e7a-8fbd-9de7849bdd54.png">


Co-factor 0.01: 
<img width="757" alt="Screenshot 2023-04-25 at 1 29 22 PM" src="https://user-images.githubusercontent.com/119648999/234355925-8da66338-187f-4576-b19b-78cc01c2c004.png">



Typically, using flow cytometry/CyTOF data we are looking for two peaks (one negative peak for the cells not expressing the marker and one positive peak for the cells that do express the marker). Is this something that we should be getting for IMC? If so, then the co-factor 0.01 would be most applicable for my downstream analysis. 

Thanks in advance!

**Comment by nilseling** [comment]
When using a co-factor of 0.01 you actually get 3 peaks: 1. all cells with expression equal to 0, 2. negative cells somewhere around 2 and 3. positive cells somewhere around 3. Did you visually check the images before segmentation? The CD3 signal to noise ratio appears quite low. In general the pixel intensities are quite low.

**Comment by zoqaiyum** [comment]
Hi @nilseling 

The CD3 signal is quite low, upon inspection of the images. Using the 0.01 co-factor, these are the expression histograms I get. For some markers like CD31, aSMA, CD68, CD11c I do see the 3 peaks you mentioned. 

<img width="328" alt="image" src="https://user-images.githubusercontent.com/119648999/235780465-4dc418cf-5ef2-4813-af88-e8872ef3deff.png">

<img width="328" alt="image" src="https://user-images.githubusercontent.com/119648999/235780492-599949b0-44d4-471c-bed7-7fe6470dc9d7.png">

<img width="328" alt="image" src="https://user-images.githubusercontent.com/119648999/235780528-8133be46-8cee-43c3-9fc6-0bfcee1180dc.png">

<img width="328" alt="image" src="https://user-images.githubusercontent.com/119648999/235780558-e918043d-2ece-41cc-97eb-dcbbdba7bf93.png">

<img width="328" alt="image" src="https://user-images.githubusercontent.com/119648999/235780592-678f66c9-1a12-493e-9174-793314a3dc2b.png">

<img width="328" alt="image" src="https://user-images.githubusercontent.com/119648999/235780615-f525c399-8316-46c1-a5f6-6246a965728c.png">


Is it advisable to proceed with this co-factor?

Thanks.

**Comment by nilseling** [comment]
To me the co-factor appears to be too low. But it's hard to give advice on this as you will need to compare downstream results against your expectations to the dataset. You could also test a `log(x + 0.01)` transformation and see if that works better.

**Comment by zoqaiyum** [comment]
Hi @nilseling 

I understand. For reference, this is my code for the log transformation: 
```
assay(sce, "exprs") <- log((counts(sce)+0.01))
dittoRidgePlot(sce, var = "CD3-170Er", group.by = "sample_id", assay = "exprs") +
    ggtitle("CD3 - after transformation")
dittoRidgePlot(sce, var = "CD68-159Tb", group.by = "sample_id", assay = "exprs") +
    ggtitle("CD68 - after transformation")
dittoRidgePlot(sce, var = "CD11c-154Sm", group.by = "sample_id", assay = "exprs") +
    ggtitle("CD11c - after transformation")
dittoRidgePlot(sce, var = "CD103-150Nd", group.by = "sample_id", assay = "exprs") +
    ggtitle("CD103 - after transformation")
dittoRidgePlot(sce, var = "CD8a-162Dy", group.by = "sample_id", assay = "exprs") +
    ggtitle("CD8a - after transformation")
dittoRidgePlot(sce, var = "CD69-160Gd", group.by = "sample_id", assay = "exprs") +
    ggtitle("CD69 - after transformation")
dittoRidgePlot(sce, var = "Pan-Cytokeratin-148Nd", group.by = "sample_id", assay = "exprs") +
    ggtitle("Pan-Cytokeratin - after transformation")


dittoRidgePlot(sce, var = "aSMA-141Pr", group.by = "sample_id", assay = "exprs") +
    ggtitle("aSMA - after transformation")
dittoRidgePlot(sce, var = "CD31-151Eu", group.by = "sample_id", assay = "exprs") +
    ggtitle("CD31 - after transformation")
dittoRidgePlot(sce, var = "CD49a-174Yb", group.by = "sample_id", assay = "exprs") +
    ggtitle("CD49a - after transformation")
```

These are what the expressions look like: 
![image](https://user-images.githubusercontent.com/119648999/236029938-12efb980-01d6-46ea-9fa5-2b21b5259397.png)

![image](https://user-images.githubusercontent.com/119648999/236030894-a58dfea1-780f-42e0-b35f-a3045274a312.png)

![image](https://user-images.githubusercontent.com/119648999/236030949-de3f66ea-5db0-4554-befe-c11057030e23.png)

![image](https://user-images.githubusercontent.com/119648999/236031103-804badca-f56c-4349-b589-07fb7765e2e7.png)

![image](https://user-images.githubusercontent.com/119648999/236031330-7207556b-302c-46b6-a0b4-8ff060542d0b.png)

![image](https://user-images.githubusercontent.com/119648999/236031435-f499e3b6-b37c-42b7-bf1d-69e6e6cf240e.png)

The scale has gone to the negative now.

**Comment by nilseling** [comment]
I would say you pick a co-factor that you are happy with and proceed to downstream analysis to check if the results make sense. Just by looking at the distributions it's hard to tell what the best co-factor is. I'm closing this issue for now.
