### ISSUE TITLE
Run normalize with only 1 sample

### ISSUE THREAD

**Issue by rebekahdadey** [BodenmillerGroup/IMCDataAnalysis#56]
Hello:

I am analyzing IMC data from **one** sample. I believe that it is having trouble normalizing since it is only 1 sample. 
When I get to the normalization steps,  I can run the first normalization step but cannot run the next normalization step to clip maximum intensity. If I only run normalization and skip the clipping of maximum intensity, I cannot plotPixels as the image is not a CytoImage List. Are you able to help? Thanks

`img_ids <- sample(seq_len(length(images)), 1)

Normalize and clip images
cur_images <- images[img_ids] 
cur_images <- normalize(cur_images)
cur_images <- normalize(cur_images, inputRange = c(0, 0.2))

pdf("Sample_cell_segmentation_MESMER.pdf")
plotPixels(cur_images,
           mask = masks[img_ids],
           img_id = "sample_id",
           missing_colour = "white",
           colour_by = c("aSMA","Pan-Keratin","CD45","CD8","CD4","Collagen"),
           colour = list(aSMA = c("black", "yellow"),
                         `Pan-Keratin` = c("black", "red"),
                         CD45 = c("black", "green"),
                         CD8 = c("black", "blue"),
                         CD4=c("black", "orange"),
                         Collagen=c("black", "white")),
           image_title = NULL,
           legend = list(colour_by.title.cex = 0.7,
                         colour_by.labels.cex = 0.7))
dev.off()`

**Comment by nilseling** [comment]
Hi @rebekahdadey 

I can't reproduce this error. Could you please post the output of `cur_images` after each normalization step here? If you get an error message, please also post it here. I would also need the output of `sessionInfo()`. Thanks!

**Comment by rebekahdadey** [comment]
Hi! Thanks. So I found out that if I don't load all my packages and only load imcRtools and cytomapper, then there is no problem with the normalization steps. Not sure the exact problem, but maybe another package is interfering. 

Thanks for your help!

**Comment by nilseling** [comment]
Yes, I think I have seen that before. You can also call `cytomapper::normalize()` to be safe.
