### ISSUE TITLE
One of my gated cells is missing (9.3 Classification Approach)

### ISSUE THREAD

**Issue by zoqaiyum** [BodenmillerGroup/IMCDataAnalysis#57]
Hi @nilseling 

I am following section 9.3 Classification Approach. I completed downloading 7 gates (for 7 different cell types) and followed step 9.3.3 to read in the files: 

```
library(SingleCellExperiment)
label_files <- list.files("data/gated_cells", 
                          full.names = TRUE, pattern = ".rds$")

# Read in SCE objects
sces <- lapply(label_files, readRDS)

# Merge SCE objects
concat_sce <- do.call("cbind", sces)
```

To check if I have all my gated cells, I checked it through this: 

`unique(label_files)`

The output for the code above is this: 
<img width="450" alt="Screenshot 2023-05-18 at 4 20 28 PM" src="https://github.com/BodenmillerGroup/IMCDataAnalysis/assets/119648999/d144c205-5744-449e-8635-e2179cdce99e">

In the next step, I applied the filter function as described: 
```
filter_labels <- function(object, 
                          label = "cytomapper_CellLabel") {
    cur_tab <- unclass(table(colnames(object), object[[label]]))
    
    cur_labels <- colnames(cur_tab)[apply(cur_tab, 1, which.max)]
    names(cur_labels) <- rownames(cur_tab)
    
    cur_labels <- cur_labels[rowSums(cur_tab) == 1]
    
    return(cur_labels)
}
```

Next, I try to see if the function has been applied to all my cells: 
```
#all cells
labels <- filter_labels(concat_sce)

unique(labels)
```

However, the output of unique(labels) is the following: 
[1] "CD14+CD11c+" "CD3-CD68+"   "CD45+"       "CD3-CD14+"   "CD3+CD8a+"   "CD3-CD11c+" 

I am missing one cell-type, CD103+CD11c+, and cannot seem to figure the problem in my coding that would have made it disappear. Would you have any ideas on this?

Additionally, when I used the interactive cytomappershiny object on my browser, I applied my gate on one sample (for example CD103+CD11c+), checked it against all the other samples, and then downloaded it once. Does it mean the gates for all the samples would have been downloaded as well or would I need to download CD103+CD11c+ gate for every sample one by one? Such that it would essentially be CD103+CD11c+_sample1, CD103+CD11c+_sample2, and so on.

Thanks in advance!

**Comment by nilseling** [comment]
Hi @zoqaiyum 

this is a bit hard to debug. What's the output of `unique(concat_sce$cytomapper_CellLabel)`? Maybe also check which cells were labelled multiple times:

```
cur_tab <- unclass(table(colnames(concat_sce), concat_sce$cytomapper_CellLabel))
cur_tab[rowSums(cur_tab) > 1,]
```

And yes, you only download the gated cells of a single sample. You can check this by looking at e.g. `sces[[1]]`.
