### ISSUE TITLE
Any idea why the last error occurs?

### ISSUE THREAD

**Issue by StiThor** [BodenmillerGroup/IMCDataAnalysis#60]
![image](https://github.com/BodenmillerGroup/IMCDataAnalysis/assets/90035897/9de05c6c-f6c5-4af5-afd1-bf1a5c928db9)

**Comment by StiThor** [comment]
Which subscript does it refer to?

**Comment by nilseling** [comment]
Unfortunately, I don't know what's going on there as I don't know what this data is and how you got there. Would you have anyone on your side that could help you with implementing your analysis workflow?

**Comment by nilseling** [comment]
I'm assuming this has been resolved.

**Comment by StiThor** [comment]
Yes, I managed :)

**Comment by StiThor** [comment]
This is off-topic, but I could see that there have been from what I understand major changes to HistoCat. Is this something that is up and running or still under development? I could not find anything under releases....

**Comment by nilseling** [comment]
I'm not involved with the development of HistoCat. Please open an issue here: https://github.com/SchapiroLabor/histoCAT

**Comment by StiThor** [comment]
Thanks!
