### ISSUE TITLE
Construction of spatial graphs for neighbourhood analysis

### ISSUE THREAD

**Issue by zoqaiyum** [BodenmillerGroup/IMCDataAnalysis#62]
Hi @nilseling 

I wanted to conduct the spatial analysis (Section 12 https://bodenmillergroup.github.io/IMCDataAnalysis/performing-spatial-analysis.html) on my dataset, however when I try to do this first step: 

```
library(imcRtools)
sce2 <- buildSpatialGraph(sce2, img_id = "sample_id", type = "knn", k = 20)
sce2 <- buildSpatialGraph(sce2, img_id = "sample_id", type = "expansion", threshold = 20)
sce2 <- buildSpatialGraph(sce2, img_id = "sample_id", type = "delaunay", max_dist = 50) 
```

It is giving me an error: Error in .valid.buildSpatialGraph.input(object, type, img_id, k, threshold, :
'coords' not in colData(object).

I think this is because I did not use the steinbock framework to upload my files. I simply ran these lines of code as an alternative to steinbock: 
<img width="911" alt="Screenshot 2023-06-05 at 11 51 03 AM" src="https://github.com/BodenmillerGroup/IMCDataAnalysis/assets/119648999/c5aaf535-51b4-41ba-b916-ebf467a62f52">

I also performed some processing to obtain "sample_id" and the results of my sce are below: 
<img width="909" alt="Screenshot 2023-06-05 at 11 51 37 AM" src="https://github.com/BodenmillerGroup/IMCDataAnalysis/assets/119648999/032a0e6e-7f02-4767-9453-f61da93faef7">

I have been able to run pretty much all the analysis provided in the documentation on the basis of this input, however I noticed that using steinbock you ran this code to construct a spatial graph by expanding the individual cell masks by 4 pixels.

```
# single-cell feature extraction
steinbock measure intensities --masks masks_deepcell
steinbock measure regionprops --masks masks_deepcell
steinbock measure neighbors --masks masks_deepcell --type expansion --dmax 4
```

Could you please tell me how do I expand the cell masks by 4 pixels to make neighbours without steinbock? If I absolutely need steinbock, how do I amend my previous code (loadImages) that I used to input my images and masks? 

Thanks in advance!

**Comment by nilseling** [comment]
Hi @zoqaiyum 

First, the `measureObjects` function writes the x-y location into `colData(sce)[,c("m.cx", "m.cy")]`. So 

```
sce2 <- buildSpatialGraph(sce2, img_id = "sample_id", type = "knn", k = 20, coords = c("m.cx", "m.cy")) 
```

etc., should work.

Second, the `buildSpatialGraph` function only constructs graphs based on the centroids of cells. You will need steinbock for mask expansion. If you have the masks and the images, you can use the steinbock calls as shown above to measure intensities, regionprops and neighbors and you can use the `read_steinbock` function to read in the single-cell data with graphs into a `SpatialExperiment` object.

**Comment by zoqaiyum** [comment]
Hi @nilseling 

Adding the coords to the buildSpatialGraph worked. 

Is it possible to do loadImages in RStudio for loading of images and masks and then just using the steinbock framework for mask expansion? If so, would this be the sequence of steps: 

Step 1 in RStudio (read in masks which are ilastik probabilities masks): 

```
#Read in masks
allmasks<- loadImages("~/Documents/Aortic Valve Project/Normalized TIFFs and Segmentation Masks2/Masks", as.is = TRUE)
```

Step 2 in RStudio (read in images): 

```
#Read in images
allimages<- loadImages("~/Documents/Aortic Valve Project/Normalized TIFFs and Segmentation Masks2/Images", single_channel = TRUE)
```

Step 3 in RStudio (process dataframe and build sce object): 

```
mcols(allimages)<- mcols(allmasks)<- DataFrame(sample_id = names(allimages))
sce<- measureObjects(allmasks, image = allimages, img_id = "sample_id")
sce
```

Step 4 in steinbock framework: 

`pip install steinbock`

Now I am confused about my next lines of code as I have zero experience with Python. 
-Should Step 5 be loading my masks? If so, how do I do that? Currently, my masks are in this pathway (as seen on RStudio): ~/Documents/Aortic Valve Project/Normalized TIFFs and Segmentation Masks2/Masks

-Should Step 6 be this line of code: steinbock measure neighbors --allmasks --type expansion --dmax 4

For clarification, I am using the Colaboratory Python interface on the Google platform: https://colab.research.google.com/ for running steinbock

<img width="1331" alt="Screenshot 2023-06-05 at 1 50 34 PM" src="https://github.com/BodenmillerGroup/IMCDataAnalysis/assets/119648999/f7aa061e-05c1-4f54-9e69-10731812e68c">


Any help would be wonderful!!

**Comment by nilseling** [comment]
Hi @zoqaiyum 

as this doesn't relate to the  `IMCDataAnalysis` repo anymore but is `steinbock` specific, please open a new issue at https://github.com/BodenmillerGroup/steinbock/issues. I have little experience with using `steinbock` as a python package but @Milad4849 can help you there. But I believe you will first need to get your images into the format that `steinbock` supports. See https://bodenmillergroup.github.io/steinbock/latest/file-types/
