### ISSUE TITLE
Add cytoviewer to workflow

### ISSUE THREAD

**Issue by lassedochreden** [BodenmillerGroup/IMCDataAnalysis#63]
Hi @nilseling, 

as discussed, it would be great to add [cytoviewer](https://github.com/BodenmillerGroup/cytoviewer) to the workflow. 

Potential inclusion during: 
Chapter 7 (Image- and cell-level quality control) 
Chapter 11 (Image visualization)

Feel free to also assign me.

**Comment by nilseling** [comment]
Done in #69
