### ISSUE TITLE
Unusually low marker expression?

### ISSUE THREAD

**Issue by Yanira1208** [BodenmillerGroup/IMCDataAnalysis#66]
Hello! 

We've run our samples through pre-processing and are currently working through the quality control section of IMC data analysis. We have, however, determined that some of our markers are not being captured appropriately for some reason (see screenshot of heatmap and segmentation).  When we look at these marker expressions via MCD viewer we are seeing that expression is comparable to the other markers and is present. Any idea why this may be? Would this be an issue with the pre-processing? 

Markers with unusually low expression: 
CD3
CD20
Ki67
CD33
CD163
PD-1

![Screenshot (59)](https://github.com/BodenmillerGroup/IMCDataAnalysis/assets/104864778/12a42f62-72af-417c-942b-cef7511d5cad)

![Screenshot (62)](https://github.com/BodenmillerGroup/IMCDataAnalysis/assets/104864778/eef65ba5-7b00-4faf-a256-5249f2b38865)

**Comment by nilseling** [comment]
I believe the MCD viewer scales the marker intensities to increase the contrast. What is the pixel intensity range (0 - ?) for CD3, CD20, etc and what is the pixel intensity range for the more abundant marker (e.g., CD68, aSMA, etc)?

**Comment by Yanira1208** [comment]
Ah yes, it appears that there may have been an issue with the antibody binding for some of these which would explain the lower expression values. Nothing to do on your end, thank you for helping me see this! Feel free to close this out :)
