### ISSUE TITLE
How to exclude an image from analysis if cell density is too low.

### ISSUE THREAD

**Issue by Will760** [BodenmillerGroup/IMCDataAnalysis#71]
Hi,

I am following the 'Analysis workflow for IMC data'. The document is fantastic and really easy to work through. My question regards step 7: Image and cell-level quality control, specifically where the cell density per image plot is created. looking at this plot, I can see that one of my images has a really low cell density. Further investigation with cytomapper shows that this image has been cut-off whilst imaging and I would therefore like to exclude it from subsequent analysis. 

How can I 'cleanly' remove this image and all associated data from the SpatialExperiment object (if necessary) such that is no longer considered in the downstream analysis?

Best wishes and thank you so much for putting this resource together!

Will

**Comment by lassedochreden** [comment]
Hi @Will760, 

thanks a lot for the kind feedback and for using this resource! 

You can exclude an image from the SpatialExperiment object (here called `spe`) as follows: 

`spe <- spe[,!spe$img_id %in% img_id_remove]`

This call assumes that your image identifiers are stored in the `colData` slot of the SpatialExperiment object under `img_id` and that you stored the image identifier of the image that you want to remove in a vector called `img_id_remove`.  

Hope this helps. Let us know if you have more questions.

**Comment by Will760** [comment]
Thank you Lasse, works perfectly.
Best wishes,

Will

**Comment by Will760** [comment]
Hi all,

I just wanted to add to this in case it is useful for anyone else encountering this. Following the removal of these images, everything worked perfectly fine up until section 9.3.1 Manual Labelling of Cells ([link](https://bodenmillergroup.github.io/IMCDataAnalysis/cell-phenotyping.html#manual-labeling-of-cells)). At this point I encountered the following error:

`library(cytomapper)
if (interactive()) {
  cytomapperShiny(object = spe, mask = masks2, image = images2, 
                  cell_id = "ObjectNumber", img_id = "sample_id")
}
`

`Error in .valid.sce.shiny(object, img_id, cell_id, image, mask) : 
  Please provide a unique image/mask
for every sample stored in 'object'.`

After a bit of playing around, I realised that the spe$sample_id was 6 images shorter than the cytoimagelists 'masks' and 'images'. I think this discrepancy and the left over objects in the two cytoimagelists may have been the cause for this error. To fix this, I removed these additional images from the two cytoimagelists in the following way:

`images2 <- images[(names(images) %in% spe$sample_id)]
masks2 <- masks[(names(images) %in% spe$sample_id)]`

Then, altered the original code to `...mask = masks2, image = images2`

This fix then seemed to work for me. Hope this helps anyone in the same position.
