### ISSUE TITLE
PlotPixels: Segmentation masks must only contain integer values

### ISSUE THREAD

**Issue by giuliospinozzi** [BodenmillerGroup/IMCDataAnalysis#72]
Hi, I would like to plot multi-channel markers in a single image but I receive this error:
Error in .valid.mask(mask, img_id) : 
  Segmentation masks must only contain integer values.

when I try to execute this code:

`ROI_to_use = 8
clip_value = 0.3

image_to_use = images[ROI_to_use]

# Normalize and clip images
image_to_use <- cytomapper::normalize(image_to_use, separateImages = TRUE)
image_to_use <- cytomapper::normalize(image_to_use, inputRange = c(0, clip_value))

plotPixels(image_to_use,
           mask = masks[ROI_to_use],
           img_id = "sample_id",
           missing_colour = "white",
           colour_by = c("aSMA", "EGFR", "DNA1"),
           colour = list("aSMA" = c("black", "yellow"),
                         "EGFR" = c("black", "red"),
                         "DNA1" = c("black", "blue")),
                  image_title = NULL,
                  legend = list(colour_by.title.cex = 0.7,
                         colour_by.labels.cex = 0.7))`

**Comment by nilseling** [comment]
Hi @giuliospinozzi 

it means the masks that you are working with do not contain integer cell IDs (e.g. 1, 2, 3, ...).
What's the output of  `head(table(masks[[1]]))`?

Also, what's the bit-encoding of the mask TIFF files and how did you read in the masks?

**Comment by giuliospinozzi** [comment]
hi, `head(table(masks[[1]]))`:
0 1.52590218966964e-05 3.05180437933928e-05 4.57770656900893e-05 6.10360875867857e-05 
             1215803                   97                   59                   41                   75 
7.62951094834821e-05 
                  66 

how can I check the bit-encoding of TIFF image? I segmented with Steinbeck, deepcell...
I read the masks with 'masks <- loadImages(paste(path,'/masks/',sep=''), as.is = FALSE)'

**Comment by giuliospinozzi** [comment]
the problem can be `masks <- loadImages(paste(path,'/masks/',sep=''), as.is = FALSE)`. Probably I have to change to `as.is = TRUE` ?

**Comment by nilseling** [comment]
Indeed, that's the issue.
