### ISSUE TITLE
Process a single ROI

### ISSUE THREAD

**Issue by giuliospinozzi** [BodenmillerGroup/IMCDataAnalysis#73]
I segmented a MCD file with steinbock that contains 8 different ROIs. With the classical analysis the flow merged all ROIs but now I would like to process one single ROI. Is it possible to use only one ROI? In the steinbock analysis folder I have all ROIs together.

Thanks a lot

**Comment by nilseling** [comment]
There are two ways forward:

1. You remove all files in the `img`, `masks`, `regionprops`, `intensities` and `neighbors` folders that you don't need.
2. (preferred) after reading the data into a `SpatialExperiment` object, you can subset it: `spe <- spe[,spe$sample_id == "name_of_ROI"]`

Please close this issue if that worked for you.
