### ISSUE TITLE
Fast MNN batch correction: more singular values/vectors requested than available

### ISSUE THREAD

**Issue by Will760** [BodenmillerGroup/IMCDataAnalysis#74]
Dear team,

Thank you for all of your help so far. I am trying to run the fast MNN batch correction on my data but am running into an issue. As is written in the guide book I use:

```
out <- fastMNN(spe, batch = spe$patient_id,
               auto.merge = TRUE,
               subset.row = rowData(spe)$use_channel,
               assay.type = "exprs")
```

Then I get the following error:
```
Error in check_numbers(k = k, nu = nu, nv = nv, limit = min(dim(x)) -  : 
  (converted from warning) more singular values/vectors requested than available
```

I am not sure what has gone wrong and why there are not enough values/vectors. 

Best wishes,

Will

**Comment by nilseling** [comment]
Hi @Will760 

Please have a look at the section again: https://bodenmillergroup.github.io/IMCDataAnalysis/batch-effects.html#perform-sample-correction

I have added a note on how to avoid this Error/Warning  (you would need to set the `d` parameter to some number lower than the number of channels). I'm surprised that this is an Error now and will try to reproduce this on my end. Please close this issue if it's resolved.

**Comment by Will760** [comment]
Thank you very much @nilseling!

I altered the d parameter and the error was solved, but then got the second warning mentioned in the guide, which was of course solved with the other fix. All working now, thanks for the support.

Best wishes,

Will
