### ISSUE TITLE
10.4.1 Publication-ready ComplexHeatmap not generating anything but no errors

### ISSUE THREAD

**Issue by Will760** [BodenmillerGroup/IMCDataAnalysis#76]
Hi,

I am trying to run 10.4.1 Publication-ready ComplexHeatmap from the [guide](https://bodenmillergroup.github.io/IMCDataAnalysis/single-cell-visualization.html#publication-ready-complexheatmap) however, although all the code runs fine with no errors, nothing is generated. I checked back and other plot earlier in the script still generate, but for whatever reason, these plots do not. 

I have tried to run them individually, instead of h_list'ing them and drawing etc. to see if there was anything wrong with any of the plots, but this also does not generate any plots.
 
`Heatmap(t(assay(celltype_mean, "exprs")),
                  column_title = "type_markers",
                  col = col_exprs,
                  name= "mean exprs",
                  show_row_names = TRUE, 
                  show_column_names = TRUE)`

The only warning I get is when they get combined at the h_list stage:

`Warning messages:
1: Heatmap/annotation names are duplicated: mean exprs 
2: Heatmap/annotation names are duplicated: mean exprs 
3: Heatmap/annotation names are duplicated: mean exprs 
4: Heatmap/annotation names are duplicated: mean exprs`

I understand this is probably very little detail to go on. Is there any checks I can run to see why the plots aren't generating so I can provide some more details?

Thanks for your help as always!!!

Best wishes,
Will

**Comment by nilseling** [comment]
Hmm, it's indeed a bit hard to figure out what's going on. Did you check if the plots appear under the code chunk in the Rmd file? What if you "knit" the Rmd file, do they appear in the rendered html? If you copy the code into a .R file, do they show up on the graphics device? I'm assuming you are working with RStudio, right?

**Comment by Will760** [comment]
Hi Nils,
Thanks for your response.
I moved out of the rmd file a while ago and have been copying and altering the code in an .R file in Rstudio. Nothing shows up in the plotting window and no errors are produced.

Best wishes,

Will

**Comment by nilseling** [comment]
In that case, execute `dev.off()` a number of times until you get the following error:

```
Error in dev.off() : cannot shut down device 1 (the null device)
```

and try again. You can also restart the R session and try again.

**Comment by Will760** [comment]
Thanks Nils,

This worked for me. Thank you for the help!

Best wishes,
Will
