### ISSUE TITLE
11.2.1 Visualizing metadata: Error in .valid.colour(...)

### ISSUE THREAD

**Issue by Will760** [BodenmillerGroup/IMCDataAnalysis#77]
Hi Nils,

I am attempting to visualize a single cell type on the segmented image in the following manner:

```
CD8 <- spe[,spe$celltype == "CD8+ T Cells"]

plotCells(cur_masks,
          object = CD8, 
          cell_id = "ObjectNumber", 
          img_id = "sample_id",
          colour_by = "celltype",
          colour = list(celltype = c(CD8 = "red")),
          missing_colour = "white")

```
I get the following error:

```
'Error in .valid.colour(colour, colour_by, outline_by, object, image = NULL) : 
  Please specify colours for all 'colour_by' levels.

```

Should setting `missing_colour = white` not specify the colour for all other levels as white? What have I done wrong.

Best wishes and Thank you!!!,
Will

**Comment by nilseling** [comment]
The level you want to color is `CD8+ T Cells` and not `CD8`: `colour = list(celltype = c("CD8+ T Cells" = "red"))`

**Comment by Will760** [comment]
Thank you!
