### ISSUE TITLE
12.1 Spatial Interaction Graphs: No graph, only title

### ISSUE THREAD

**Issue by Will760** [BodenmillerGroup/IMCDataAnalysis#78]
Hello,

Sorry for so many questions! I am building the spatial interactions graphs in section 12.1 and then visualising them in 12.2.

When I ran the KNN spatial interaction graph, I initially got the following error:

```
Error: BiocParallel errors
  1 remote errors, element index: 5
  28 unevaluated and other errors
  first remote error:
Error: BiocParallel errors
  1 remote errors, element index: 1
  0 unevaluated and other errors
  first remote error:
Error in (function (to_check, X, clust_centers, clust_info, dtype, nn, : (converted from warning) detected tied distances to neighbors, see ?'BiocNeighbors-ties'
```
I then did `options(warn = 0)` and was able to complete the run, but got the following warnings:

```
The returned object is ordered by the 'patient_id' entry.
Warning messages:
1: In (function (to_check, X, clust_centers, clust_info, dtype, nn,  :
  detected tied distances to neighbors, see ?'BiocNeighbors-ties'
2: In (function (to_check, X, clust_centers, clust_info, dtype, nn,  :
  detected tied distances to neighbors, see ?'BiocNeighbors-ties'
```

I continued, and ran the DeLauney and Expansion spatial interaction graphs without error or warning.

They definitely exist:

```
> colPairNames(spe)
[1] "neighborhood"                "knn_interaction_graph"       "expansion_interaction_graph"
[4] "delaunay_interaction_graph" 
```

The problem then arises when I try to run `plotspatial()`. The Steinbock interaction graph works fine and generates a perfect spatial interaction graph but the remaining 3 all run for about a second then just simply print the name of the interaction graph in the top left of the plotting window in RStudio. 
![image](https://github.com/BodenmillerGroup/IMCDataAnalysis/assets/113446078/fbc7fe70-d0b5-44bf-91e1-515723c94359)
I tried running dev.off() a few times on the off chance that fixed this but to no avail.

Thanks for all of your help so far, I really do appreciate it!

Best wishes,

Will

**Comment by nilseling** [comment]
Hi @Will760 

unfortunately I can't help you with this issue as it relates to your RStudio setup and not the `IMCDataAnalysis` repository or any of the tools we provide. I highly recommend to work with Rmd files and knitting them to html to see if this issue can be resolved.

**Comment by Will760** [comment]
Ok Thank you anyway!

Best wishes,

Will
