### ISSUE TITLE
Subclustering of PhenoGraph clusters

### ISSUE THREAD

**Issue by marleneweiss** [BodenmillerGroup/IMCDataAnalysis#79]
Hi,

I am hoping that you can provide some information on how to perform subclustering with PhenoGraph clusters generated in imcRtools (for example to further subcluster a cluster containing all types of immune cells). 
Help is highly appreciated!

Best,
Marlene

**Comment by nilseling** [comment]
Hi @marleneweiss 

How about something like this (untested):

```
sub_spe <- spe[,spe$celltype == "T_cell"]

T_mat <- t(assay(sub_spe, "exprs"))

set.seed(230824)
T_out <- Rphenograph(T_mat, k = 45)

T_clusters <- factor(membership(T_out[[2]]))

sub_spe$T_clusters <- T_clusters
```

If you then need to store the sub-cluster IDs in the original `SPE` object:

```
sub_clusters <- spe$celltype
sub_clusters[spe$celltype == "T_cell"] <- as.character(T_cluster)
spe$sub_clusters <- sub_clusters
```

**Comment by marleneweiss** [comment]
Thank you, this works great!
Would you also be able to tell me the best approach to split "exprs" data by indication stored in the colData slot in order to generate (violin) plots just with the partial exprs data (diseased vs. control)? I have been trying subsetting/splitting/filtering, but nothing has worked until now.

**Comment by nilseling** [comment]
Please have a look at the [Single-cell visualization section](https://bodenmillergroup.github.io/IMCDataAnalysis/single-cell-visualization.html). I believe you are looking for something like [this](https://bodenmillergroup.github.io/IMCDataAnalysis/single-cell-visualization.html#violin-plot-visualization)

**Comment by marleneweiss** [comment]
Yes, this is exactly what I am referring to. I have analyzed all samples together, so I have overall exprs data grouped for three indications, but I would like to plot just partial exprs data, so exprs(control), exprs(condition1), exprs(condition2). I was hoping that splitting the exprs data is possible at this point rather than starting from scratch and having to generate single spes for the different conditions.

**Comment by marleneweiss** [comment]
Something like this (not working):
exprs_split <- split(exprs, colData(spe)$indication == "control")

**Comment by nilseling** [comment]
Hmm, I'm not quite sure exactly what you want to plot. But you can test something like:

```
library(dittoSeq)

dittoPlot(spe, var = "Ecad", group.by = "celltype", assay = "exprs", split.by = "indication")
```

or

```
multi_dittoPlot(test, vars = rownames(test), group.by = "indication", assay="exprs")
```

**Comment by marleneweiss** [comment]
Thank you, the first approach is working ok.  However, the plotExpression function has a nicer output for visualization. When I try the split.by = "indication" addition there, it gives out the error: unused argument (split.by = "indication").

I was hoping to divide/split the exprs values **before** putting them into the function. Then I would have them separated by indication for all further analysis. Do you see a way do to do that? The aim is to then be able to use "exprs_control", "exprs_condition1", "exprs_condition2" as separate inputs rather than the overall "exprs" in the function below. 

plotExpression(spe[,cur_cells], 
               features = rownames(spe)[rowData(spe)$marker_class == "type"],
               x = "celltype", 
               exprs_values = "exprs", 
               colour_by = "celltype") +
    theme(axis.text.x =  element_text(angle = 90))+
    scale_color_manual(values = metadata(spe)$color_vectors$celltype)

**Comment by nilseling** [comment]
So you want to subset the SPE object based on condition?

```
spe_control <- spe[,spe$indication == "control"]
spe_condition1 <- spe[,spe$indication == "condition1"]
spe_condition2 <- spe[,spe$indication == "condition2"]
```
 and then call the `plotExpression` function on each SPE object. Please make sure to use the same y scale for all your plots.

**Comment by marleneweiss** [comment]
This approach makes sense! Unfortunately the specific code is not working - the three separate spe don't contain any cells/colnames:

class: SpatialExperiment 
dim: 37 0 
metadata(1): color_vectors
assays(2): counts exprs
rownames(37): ASMA Calbindin ... Membrane1 Membrane2
rowData names(8): channel name ... channel_name marker_class
colnames(0):
colData names(17): sample_id ObjectNumber ... sub_clusters clusters2
reducedDimNames(4): UMAP TSNE fastMNN UMAP_mnnCorrected
mainExpName: NULL
altExpNames(0):
spatialCoords names(2) : Pos_X Pos_Y
imgData names(1): sample_id

It's 90468 cells/colnames in the overall spe:

class: SpatialExperiment 
dim: 37 90468 
metadata(1): color_vectors
assays(2): counts exprs
rownames(37): ASMA Calbindin ... Membrane1 Membrane2
rowData names(8): channel name ... channel_name marker_class
colnames(90468): cell1 cell2 ... cell90467 cell90468
colData names(17): sample_id ObjectNumber ... sub_clusters clusters2
reducedDimNames(4): UMAP TSNE fastMNN UMAP_mnnCorrected
mainExpName: NULL
altExpNames(0):
spatialCoords names(2) : Pos_X Pos_Y
imgData names(1): sample_id

**Comment by nilseling** [comment]
You will need to adapt the code based on your needs. I cannot guess how your SPE object looks like.

**Comment by marleneweiss** [comment]
Ok, I will. Thank you again for taking your time to help and your very helpful input!

**Comment by nilseling** [comment]
Sure thing. I will close this issue now.
