### ISSUE TITLE
Same sample colors between different heatmaps

### ISSUE THREAD

**Issue by giuliospinozzi** [BodenmillerGroup/IMCDataAnalysis#80]
I have generated two heatmap, as in picture
![image](https://github.com/BodenmillerGroup/IMCDataAnalysis/assets/9041243/6e698bd4-d5d2-4da3-b27d-1477f77aa71f)

I would like to use the same sample_id color between heatmaps (all markers without and with clusters).
Is it possible?

**Comment by nilseling** [comment]
Hi @giuliospinozzi 

you would first need to generate a color vector for the `sample_id`'s:

```
col_sample_id <- setNames(dittoColors(1)[1:length(unique(spe$sample_id))],
                          unique(spe$sample_id))
```

which you can then use in your heatmaps:

```
dittoHeatmap(..., annotation_colors = list(sample_id = col_sample_id))
```

You can also use this color vector in any `ggplot` visualization.
