### ISSUE TITLE
Number of cell for each sample

### ISSUE THREAD

**Issue by giuliospinozzi** [BodenmillerGroup/IMCDataAnalysis#81]
There is a way to have the number of cells for the object "spe" for each "sample_id"? Just numbers

**Comment by nilseling** [comment]
I guess you are looking for `table(spe$sample_id)`. Please keep in mind that these issues are meant for general problems with the code or questions regarding the content of the book. I unfortunately don't have the capacity to answer questions regarding basic R code. Please have a look if you can find someone on your side to help you with the R analysis.
