### ISSUE TITLE
Question about batch effect correction

### ISSUE THREAD

**Issue by EmilyZou123** [BodenmillerGroup/IMCDataAnalysis#83]
Dear team:
  
![image](https://github.com/BodenmillerGroup/IMCDataAnalysis/assets/117978342/110c2280-2200-492f-9cfc-f8ffadd9b970)
![image](https://github.com/BodenmillerGroup/IMCDataAnalysis/assets/117978342/ef3afb55-ade8-4bbd-9551-bb7372c92346)

I am puzzled that when looking at expression of each marker after correction, we still use "exprs" instead of the corrected data.

**Comment by nilseling** [comment]
That is correct. Have a look [here](https://bioconductor.org/books/3.17/OSCA.multisample/using-corrected-values.html#using-corrected-values) for some explanation on how to work with the corrected expression counts. For us it's enough to observe if cells with similar (non-corrected) marker expression come together on the UMAP. You could also visualize the corrected marker expression but this might not be a quantitative representation of marker abundance anymore.

**Comment by EmilyZou123** [comment]
Thank you for your reply, I also want to ask a question, I use the corrected exprssion counts to do clustering, and then use the uncorrected exprssion counts to annotate cell types, is that right?

**Comment by nilseling** [comment]
I'm pretty sure you use the corrected cell embedding for clustering and not the reconstructed counts if you are following this book. Please have a look at https://bioconductor.org/books/3.17/OSCA.multisample/integrating-datasets.html#mnn-correction to understand the difference between those.

**Comment by EmilyZou123** [comment]
So after I use the corrected exprsssion counts to cluster and get the cluster label for each cell,I need to plot the heatmap like this picture to define celltypes, I use the uncorrected exprsssion counts,is that right?
![image](https://github.com/BodenmillerGroup/IMCDataAnalysis/assets/117978342/93474261-a845-4fe2-96ab-4238fb6b803b)

**Comment by nilseling** [comment]
Yes. And you are not using the corrected expression counts but the corrected cell embeddings for clustering.

**Comment by EmilyZou123** [comment]
I get it,thanks

**Comment by nilseling** [comment]
Great, I'll close this issue now.
