### ISSUE TITLE
packages dosen't contain needed functions

### ISSUE THREAD

**Issue by ghost** [BodenmillerGroup/IMCDataAnalysis#88]
library(scater)
set.seed(220225)
spe <- runUMAP(spe, subset_row = rowData(spe)$use_channel, exprs_values = "exprs")

Error in irlba::irlba(L, nv = n, nu = 0, maxit = iters) : 
  function 'as_cholmod_sparse' not provided by package 'Matrix'

I run a code in R on Mac. I get this error. I download all the packages (Matrix, scater and irlba) but there is still the error. 
How can I solve this problem?

**Comment by lassedochreden** [comment]
Hi @GiCarlu, 

Please try running: 
`install.packages("Matrix", type = "source")`  
`install.packages("irlba", type = "source")`

This will build these packages again from source and was proposed in following issues: 
https://github.com/satijalab/seurat/issues/8100
https://github.com/bwlewis/irlba/issues/70

Also it would be great if you could provide your `sessionInfo()`, if you open an issue. 

Let us know whether this worked for you. If yes, please close the issue.

**Comment by ghost** [comment]
Thank you very much, it worked for me. 

sorry for the missing section info, but not being an bioinformatician myself, I am not really sure about what I am supposed to do. 

thank you very much again. I'm closing the issue.
