### ISSUE TITLE
8.3 Seurat correction - problems 

### ISSUE THREAD

**Issue by ghost** [BodenmillerGroup/IMCDataAnalysis#89]
features <- rownames(spe)[rowData(spe)$use_channel]
> seurat.list <- lapply(X = seurat.list, FUN = function(x) {
+   x <- ScaleData(x, features = features, verbose = FALSE)
+   x <- RunPCA(x, features = features, verbose = FALSE, approx = FALSE)
+   return(x)
+ })
Warning messages:
1: Key ‘PC_’ taken, using ‘pca_’ instead 
2: Key ‘PC_’ taken, using ‘pca_’ instead 
> anchors <- FindIntegrationAnchors(object.list = seurat.list, 
+                                   anchor.features = features,
+                                   reduction = "rpca", 
+                                   k.anchor = 20)
Scaling features for provided objects
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=00s  
Computing within dataset neighborhoods
  |                                                  | 0 % ~calculating  Error in Embeddings(object = object.list[[x]][[nn.reduction]])[, dims] : 
  subscript out of bounds

When I do this passage of the pipeline, I receive this error, but I'm not able to correct it, because I have no experience in informatics. 

Thanks in advance

**Comment by SchulzDan** [comment]
Dear GiCarlu,

With the given information I am not sure I can help you. I assume that either the `features` or the `seurat.list` have not been properly defined. Potentially, you are also running into memory issues during processing. Impossible to tell like this.

For your consideration, if you do not have any experience with coding, please consider getting help from someone at your institution. Our book is a guide that we believe does require at least some basic R skills and we do not have the capacity to handle issues that may originate from missing coding skills. I hope you understand.

Best,
Daniel

**Comment by MoronicDroid** [comment]
Hi GiCarlu,

I've recently started IMC analysis and have been following the Bodenmiller workflow. After integrating my data into the workflow, I came across the same error message as you on the Seurat part: 

Scaling features for provided objects
|++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=00s
Computing within dataset neighborhoods
| | 0 % ~calculating Error in Embeddings(object = object.list[[x]][[nn.reduction]])[, dims] :
subscript out of bounds

Did you manage to solve this? If so, could you help nudge me in the right direction please.

Thanks in advance,
T

**Comment by nilseling** [comment]
It might be worth switching to Seurat V5 (they provide documentation on how to integrate data) and/or raising an issue there.
