### ISSUE TITLE
Read in and consolidate labeled data(remove-doublets)phenotyping section.

### ISSUE THREAD

**Issue by SimonSichone** [BodenmillerGroup/IMCDataAnalysis#91]
The code below keeps giving me an error. (Error in `[[<-`(`*tmp*`, name, value = c(Patient1_001_1 = "unlabeled",  : 
  46215 elements in value to replace 45687 elements).
How can I go about or solve it? to be more specific (spe$cell_labels <- spe_labels).

labels <- filter_labels(concat_spe)

cur_spe <- concat_spe[,concat_spe$cytomapper_CellLabel != "Tumor"]

non_tumor_labels <- filter_labels(cur_spe)

additional_cells <- setdiff(names(non_tumor_labels), names(labels))

final_labels <- c(labels, non_tumor_labels[additional_cells])

# Transfer labels to SPE object
spe_labels <- rep("unlabeled", ncol(spe))
names(spe_labels) <- colnames(spe)
spe_labels[names(final_labels)] <- final_labels
spe$cell_labels <- spe_labels

# Number of cells labeled per patient
table(spe$cell_labels, spe$patient_id)

**Comment by nilseling** [comment]
These cell numbers don't correspond to the data presented in the workflow. Please specify what exactly you are doing. It seems like your SPE object does not match the labelled cells. It might be better to start over and follow the workflow step by step.

**Comment by SimonSichone** [comment]
I was trying out the same data on the GitHub trying to replicate it. I will start over again and see what I might have missed.

**Comment by nilseling** [comment]
Please use the newest version of the scripts and the packages/software

**Comment by SchulzDan** [comment]
I will close this issue due to inactivity
