### ISSUE TITLE
Analysis workflow for IMC data after segmentation in HALO

### ISSUE THREAD

**Issue by alexeykb** [BodenmillerGroup/IMCDataAnalysis#92]
Hello!
We currently have CODEX data  after segmentation in HALO. I was curios, if there is a way to use this segmentated dataset  for further downstream analysis at the IMC data analysis workflow , for instance starting from the chapter 5 (read in the data). As far as I understood, it should be in the steinbock format for further process in current pipeline. Do you know if there is a way to integrate it, or I should perform resegmentation of the data in the steinbock ?

Thank you
Best regards
Alexey

**Comment by Milad4849** [comment]
@alexeykb 

Your question concerns a different package [IMCDataAnalysis](https://bodenmillergroup.github.io/IMCDataAnalysis/), please submit your issue over there.

**Comment by SchulzDan** [comment]
Hi @alexeykb

I think you don't need to re-segment your data. You can construct a spatial experiment using your segmented single-cell data. For reference please see here: https://www.bioconductor.org/packages/release/bioc/vignettes/SpatialExperiment/inst/doc/SpatialExperiment.html#2_Object_construction
To be able to run the IMCDataAnalysis workflow as smooth as possible I recommend paying attention to the names you assign for your colData during object construction. E.g. in the IMCDataAnalysis book we refer to the unique image identifier as "sample_id". You can find the names in section five of the IMCDataAnalysis book.

Hope that helps.
Best,
Daniel
