### ISSUE TITLE
Problem with confusion matrix

### ISSUE THREAD

**Issue by RiccardoSin** [BodenmillerGroup/IMCDataAnalysis#94]
After the random forest training i encounter this problem when generating the confusion matrix:

cm <- confusionMatrix(data = cur_pred, 
+                       reference = factor(test_spe$cell_labels), 
+                       mode = `"everything")

Error in confusionMatrix.default(data = cur_pred, reference = factor(test_spe$cell_labels),  : 
  the data cannot have more levels than the reference. 

I tried re-running the codes from the beginning without applying anything but the needed changes for the data paths and such so i wouldn't know where this is coming from. 
Also i'm not using the training data but a personal data set.

**Comment by SchulzDan** [comment]
Hi @RiccardoSin,

not sure how to reproduce this error without any data provided. It seems that you either have missing factors in the reference or that you have not assigned factors. 
Maybe this is a starting point:
https://stackoverflow.com/questions/40516206/error-in-confusion-matrix-the-data-cannot-have-more-levels-than-the-reference

Best,
Daniel

**Comment by RiccardoSin** [comment]
Hi @SchulzDan, 
Sorry for the late response, here the spe file 
[spe.zip](https://github.com/BodenmillerGroup/IMCDataAnalysis/files/14220183/spe.zip). 

I'm running the same exact codes in parallel with my student who's using IOS and she didn'tencounter the same problem that i did so i can't really pinpoint the problem in this case.

**Comment by SchulzDan** [comment]
Hi @RiccardoSin,

it seems that you have unmatched cell labels in your training and test data. I also noticed that you labelled very few cells e.g. 5 Macro and 3 Metastasis in training_spe and only 1 Macro and no Metastasis in the test_spe. This is where the error orginates from.  I recommend either labelling more cells and making sure that training  and test data contain all cells or remove the ones that are so rare. I don't know why your student can run the code, it should throw an error.
I will close this issue.

Best,
Daniel
