### ISSUE TITLE
train-classifier

### ISSUE THREAD

**Issue by SimonSichone** [BodenmillerGroup/IMCDataAnalysis#97]
am getting an error like this 
Error in createDataPartition(factor(lab_spe$cell_labels), p = 0.75) : 
  y must have at least 2 data points
The code is below
# Randomly split into train and test data
set.seed(221029)
trainIndex <- createDataPartition(factor(lab_spe$cell_labels), p = 0.75)
train_spe <- lab_spe[,trainIndex$Resample1]
test_spe <- lab_spe[,-trainIndex$Resample1]

**Comment by SimonSichone** [comment]
am using the scripts and data from your GitHub

**Comment by SchulzDan** [comment]
Hi  @SimonSichone,

please specify what exactly you are doing and whether you ran through the preprocessing (steinbock) and all the other parts as described in https://bodenmillergroup.github.io/IMCDataAnalysis/ withour errors. If you had errors, then please reproduce the pipeline withour errors. If you had errors, then please provide the relevant data for reprodcution.

Best,
Daniel

**Comment by SimonSichone** [comment]
Hello SchulzDan,
I an through the preprocessing. Am trying to go through the same data to reproduce it. I think it was a software problem on my part. I will update you once I update the software library in my R.
Thank you.

Simon

From: SchulzDan ***@***.***>
Date: Friday, 23 February 2024 at 16:39
To: BodenmillerGroup/IMCDataAnalysis ***@***.***>
Cc: Simon Sichone ***@***.***>, Mention ***@***.***>
Subject: Re: [BodenmillerGroup/IMCDataAnalysis] train-classifier (Issue #97)

Hi @SimonSichone<https://github.com/SimonSichone>,

please specify what exactly you are doing and whether you ran through the preprocessing (steinbock) and all the other parts as described in https://bodenmillergroup.github.io/IMCDataAnalysis/ withour errors. If you had errors, then please reproduce the pipeline withour errors. If you had errors, then please provide the relevant data for reprodcution.

Best,
Daniel
