### ISSUE TITLE
Using IMCDataAnalysis with HistoCAT-exported Data

### ISSUE THREAD

**Issue by sbeber16** [BodenmillerGroup/IMCDataAnalysis#98]
Hello, 

I am trying to use IMCDataAnalysis for spatial analysis of IMC data. I performed the PhenoGraph analysis in HistoCAT successfully and was able to export the data as csv files, each unique cell assigned to a specific cluster. Now looking to use those csv file for spatial analysis using IMCDataAnalysis package. Is there documentation on how to do this? Would it be possible?

Many thanks.

**Comment by SchulzDan** [comment]
Hi @sbeber16,

I am not sure what the output of HistoCAT looks like. Have not used it in a long long time. But surely, if you have csv files containing the expression data, metadata and cell clusters you can build an sce/spe object as described in section 5.1.3 (https://bodenmillergroup.github.io/IMCDataAnalysis/read-data.html#read-in-single-cell-information) and then use the IMCDataAnalysis workflow as a further basis.

Hope that helps.
Best,
Daniel
