### ISSUE TITLE
Data availability

### ISSUE THREAD

**Issue by jcasadogp** [BodenmillerGroup/IMCDataAnalysis#99]
Hello, 

I was wondering if it is possible to have `data/spe.rds` file. In concrete, I am curious about the barplots in [10.3.3](https://bodenmillergroup.github.io/IMCDataAnalysis/single-cell-visualization.html#barplot-visualization-1) where you color by sample and all the samples of the same patient have a specific color and different tones or intensities. Where do you store those color codes? Or is there any way of indicating that samples that have the same donor_id metadata field should have the same tones?

![image](https://github.com/BodenmillerGroup/IMCDataAnalysis/assets/80517901/3075e560-5315-4b45-9048-c2b610729c77)

Thanks in advance!

Julia

**Comment by SchulzDan** [comment]
Hi Julia,

in section [4.4](https://bodenmillergroup.github.io/IMCDataAnalysis/prerequisites.html#download-data) we show how to download all the data to build the spe object (section [5.1](https://bodenmillergroup.github.io/IMCDataAnalysis/read-data.html#read-in-single-cell-information)). Considering your question regarding coloring, as you can see in the code
`dittoBarPlot(spe, 
             var = "patient_id", 
             group.by = "celltype") +
    scale_fill_manual(values = metadata(spe)$color_vectors$patient_id)`
the colors are stored in the metadata of the spe object (not to be confused with the colData of the spe object). you can explore what is stored in the metadata simply by:
`metadata(spe)`
The colors stored in the metadata for sample_id and patient_id etc are defined in the section "Define color schemes" of section [5.3](https://bodenmillergroup.github.io/IMCDataAnalysis/read-data.html#read-images)

Hope that clarifies.
Best,
Daniel
